spring:
    datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/training
      username: postgres
      password: password
    jpa.database: POSTGRESQL
    jpa.show-sql: true
    jpa.hibernate.ddl-auto: none
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

flyway.enabled: false
